// src/lib/normativa/dati.ts
//
// Contenuti della sezione Normativa CCII. Il testo degli articoli e le
// soglie sono tratti da fonti pubbliche autorevoli (indicate in fonteUrl)
// e allineati ai correttivi vigenti. NON costituiscono testo legale
// vincolante: per l'uso ufficiale fa fede il testo pubblicato su
// Normattiva. Le note «In parole semplici» e gli esempi sono redazionali,
// a fini divulgativi. Ultima verifica dei contenuti: agosto 2026.

export interface ArticoloNormativa {
  numero: string;
  rubrica: string;
  capo: string;
  testo: string;
  soglie?: string;
  inParoleSemplici?: string;
  esempio?: string;
  fonteUrl: string;
}

export const ARTICOLI: ArticoloNormativa[] = [
  {
    numero: `2`,
    rubrica: `Definizioni`,
    capo: `Parte Prima - Titolo I (Disposizioni generali) - Capo I (Ambito di applicazione e definizioni)`,
    testo: `Art. 2, comma 1 - Ai fini del presente codice si intende per:
a) "crisi": lo stato del debitore che rende probabile l'insolvenza e che si manifesta con l'inadeguatezza dei flussi di cassa prospettici a far fronte alle obbligazioni nei successivi dodici mesi;
b) "insolvenza": lo stato del debitore che si manifesta con inadempimenti od altri fatti esteriori, i quali dimostrino che il debitore non è più in grado di soddisfare regolarmente le proprie obbligazioni;
d) "impresa minore": l'impresa che presenta congiuntamente i seguenti requisiti: 1) un attivo patrimoniale di ammontare complessivo annuo non superiore ad euro trecentomila nei tre esercizi antecedenti la data di deposito della istanza di apertura della liquidazione giudiziale o dall'inizio dell'attività se di durata inferiore; 2) ricavi, in qualunque modo essi risultino, per un ammontare complessivo annuo non superiore ad euro duecentomila nei tre esercizi antecedenti la data di deposito dell'istanza di apertura della liquidazione giudiziale o dall'inizio dell'attività se di durata inferiore; 3) un ammontare di debiti anche non scaduti non superiore ad euro cinquecentomila;
l) "parti correlate": si intendono quelle indicate come tali nel Regolamento della Consob in materia di operazioni con parti correlate;
p) "misure protettive": le misure temporanee richieste dal debitore per evitare che determinate azioni o condotte dei creditori possano pregiudicare, sin dalla fase delle trattative, il buon esito delle iniziative assunte per la regolazione della crisi o dell'insolvenza;
q) "misure cautelari": i provvedimenti cautelari emessi dal giudice competente a tutela del patrimonio o dell'impresa del debitore, che appaiano secondo le circostanze più idonei ad assicurare provvisoriamente il buon esito delle trattative.`,
    soglie: `Impresa minore (lett. d): attivo patrimoniale complessivo annuo NON superiore a euro 300.000; ricavi complessivi annui NON superiori a euro 200.000; ammontare di debiti (anche non scaduti) NON superiore a euro 500.000 - i tre requisiti devono ricorrere CONGIUNTAMENTE, riferiti ai tre esercizi antecedenti. Crisi (lett. a): orizzonte prospettico di 12 mesi.`,
    inParoleSemplici: `È il vocabolario del Codice: qui la legge dice cosa intende con «crisi», «insolvenza», «impresa minore», «misure protettive» e «misure cautelari». La distinzione chiave: la crisi è una difficoltà ancora reversibile che rende probabile l'insolvenza guardando ai flussi di cassa dei prossimi 12 mesi; l'insolvenza è lo stadio in cui l'impresa non riesce più a pagare regolarmente.`,
    esempio: `Un'azienda con incassi previsti insufficienti a coprire rate e stipendi dei prossimi 12 mesi è in «crisi». Se invece ha già smesso di pagare fornitori e dipendenti in modo stabile, è in «insolvenza».`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-i/capo-i/art2.html`,
  },
  {
    numero: `3`,
    rubrica: `Adeguatezza delle misure e degli assetti in funzione della rilevazione tempestiva della crisi d'impresa`,
    capo: `Parte Prima - Titolo I - Capo II (Principi generali) - Sezione I (Obblighi dei soggetti che partecipano alla regolazione della crisi o dell'insolvenza)`,
    testo: `1. L'imprenditore individuale deve adottare misure idonee a rilevare tempestivamente lo stato di crisi e assumere senza indugio le iniziative necessarie a farvi fronte.
2. L'imprenditore collettivo deve istituire un assetto organizzativo, amministrativo e contabile adeguato ai sensi dell'articolo 2086 del codice civile, ai fini della tempestiva rilevazione dello stato di crisi e dell'assunzione di idonee iniziative.
3. Al fine di prevedere tempestivamente l'emersione della crisi d'impresa, le misure di cui al comma 1 e gli assetti di cui al comma 2 devono consentire di: a) rilevare eventuali squilibri di carattere patrimoniale o economico-finanziario, rapportati alle specifiche caratteristiche dell'impresa e dell'attività imprenditoriale svolta dal debitore; b) verificare la sostenibilità dei debiti e le prospettive di continuità aziendale almeno per i dodici mesi successivi e rilevare i segnali di cui al comma 4; c) ricavare le informazioni necessarie a utilizzare la lista di controllo particolareggiata e a effettuare il test pratico per la verifica della ragionevole perseguibilità del risanamento di cui all'articolo 13, al comma 2.
4. Costituiscono segnali che, anche prima dell'emersione della crisi o dell'insolvenza, agevolano la previsione di cui al comma 3: a) l'esistenza di debiti per retribuzioni scaduti da almeno trenta giorni pari a oltre la metà dell'ammontare complessivo mensile delle retribuzioni; b) l'esistenza di debiti verso fornitori scaduti da almeno novanta giorni di ammontare superiore a quello dei debiti non scaduti; c) l'esistenza di esposizioni nei confronti delle banche e degli altri intermediari finanziari che siano scadute da più di sessanta giorni o che abbiano superato da almeno sessanta giorni il limite degli affidamenti ottenuti in qualunque forma purché rappresentino complessivamente almeno il cinque per cento del totale delle esposizioni; d) l'esistenza di una o più delle esposizioni debitorie previste dall'articolo 25-novies, comma 1.`,
    soglie: `Segnali/checklist (comma 4): a) debiti per retribuzioni scaduti da >= 30 giorni pari a OLTRE LA META' dell'ammontare complessivo mensile delle retribuzioni; b) debiti verso fornitori scaduti da >= 90 giorni di ammontare superiore a quello dei debiti non scaduti; c) esposizioni verso banche/intermediari scadute da > 60 giorni, oppure che abbiano superato da >= 60 giorni il limite degli affidamenti, purché rappresentino complessivamente ALMENO il 5% del totale delle esposizioni; d) rinvio alle esposizioni verso creditori pubblici qualificati ex art. 25-novies, c.1. Verifica sostenibilità/continuità: orizzonte 12 mesi.`,
    inParoleSemplici: `Impone all'imprenditore di dotarsi di assetti organizzativi, amministrativi e contabili adeguati a intercettare la crisi per tempo. Elenca i segnali d'allarme concreti (debiti verso dipendenti, fornitori, banche, creditori pubblici scaduti) e richiama gli indici, tra cui la sostenibilità del debito nei sei mesi e la continuità aziendale.`,
    esempio: `Debiti retributivi scaduti da oltre 30 giorni pari a più della metà del monte salari mensile sono un segnale tipizzato dalla norma: vanno rilevati dagli assetti e impongono di attivarsi.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-i/capo-ii/sezione-i/art3.html`,
  },
  {
    numero: `12`,
    rubrica: `Composizione negoziata per la soluzione della crisi d'impresa`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. L'imprenditore commerciale e agricolo può chiedere la nomina di un esperto al segretario generale della camera di commercio, industria, artigianato e agricoltura nel cui ambito territoriale si trova la sede legale dell'impresa, quando si trova nelle condizioni di cui all'articolo 2, comma 1, lettere a) o b), oppure quando si trova anche soltanto in condizioni di squilibrio patrimoniale o economico-finanziario che ne rendono probabile la crisi o l'insolvenza e risulta ragionevolmente perseguibile il risanamento dell'impresa. La nomina avviene con le modalità di cui all'articolo 13, commi 6, 7 e 8.
2. L'esperto agevola le trattative tra l'imprenditore, i creditori ed eventuali altri soggetti interessati, al fine di individuare una soluzione per il superamento delle condizioni di cui al comma 1, anche mediante il trasferimento dell'azienda o di rami di essa e preservando, nella misura possibile, i posti di lavoro.
3. Alla composizione negoziata non si applica l'articolo 38. Resta ferma l'applicazione dell'articolo 38, comma 2, nei procedimenti di cui agli articoli 19 e 22.`,
    inParoleSemplici: `È la norma-madre della composizione negoziata: un percorso volontario e riservato in cui un esperto indipendente aiuta l'imprenditore a trattare con i creditori per risanare l'impresa, prima e fuori dal tribunale. Si può accedere già in situazione di squilibrio che rende probabile la crisi, purché il risanamento sia ragionevolmente perseguibile.`,
    esempio: `Un'impresa con tensioni di cassa ma un mercato ancora solido chiede la nomina dell'esperto alla Camera di commercio: mantiene la gestione dell'azienda e apre le trattative con banche e fornitori con l'assistenza dell'esperto.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art12.html`,
  },
  {
    numero: `13`,
    rubrica: `Istituzione della piattaforma telematica nazionale e nomina dell'esperto`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. È istituita una piattaforma telematica nazionale accessibile agli imprenditori iscritti nel registro delle imprese attraverso il sito istituzionale di ciascuna camera di commercio, industria, artigianato e agricoltura. La piattaforma è gestita dal sistema delle camere di commercio, per il tramite di Unioncamere, sotto la vigilanza del Ministero della giustizia e del Ministero dello sviluppo economico.
2. Sulla piattaforma sono disponibili una lista di controllo particolareggiata, adeguata anche alle esigenze delle micro, piccole e medie imprese, che contiene indicazioni operative per la redazione del piano di risanamento, un test pratico per la verifica della ragionevole perseguibilità del risanamento e un protocollo di conduzione della composizione negoziata accessibili da parte dell'imprenditore e dei professionisti dallo stesso incaricati. La struttura della piattaforma, il contenuto della lista di controllo particolareggiata, le modalità di esecuzione del test pratico e il contenuto del protocollo sono definiti con decreto dirigenziale del Ministero della giustizia.
[Commi 3-5 - sintesi non verbatim] Il comma 3 stabilisce i requisiti professionali per l'iscrizione nell'elenco degli esperti (tenuto presso le camere di commercio dei capoluoghi di regione e delle province autonome), riservato a commercialisti, avvocati, consulenti del lavoro (con esperienza triennale) e ad altri soggetti aventi determinati requisiti; il comma 4 subordina l'iscrizione al possesso della specifica formazione prevista dal decreto dirigenziale di cui al comma 2; il comma 5 disciplina la presentazione della domanda agli ordini professionali e la relativa documentazione.
6. [nucleo verbatim] È costituita presso le camere di commercio dei capoluoghi di regione e delle province autonome una commissione, che nomina l'esperto, composta da un magistrato designato dal presidente della sezione specializzata in materia di impresa, da un membro designato dalla camera di commercio e da un membro designato dal prefetto del capoluogo di regione o della provincia autonoma.
7. Entro i cinque giorni lavorativi successivi al ricevimento dell'istanza la commissione nomina l'esperto tra gli iscritti nell'elenco, secondo criteri che assicurano la rotazione e la trasparenza.
[Commi 8-10 - sintesi non verbatim] Disciplinano le modalità di deliberazione della commissione, la pubblicità/comunicazione degli incarichi e il finanziamento della piattaforma.`,
    soglie: `Nomina dell'esperto da parte della commissione: entro 5 giorni lavorativi dal ricevimento dell'istanza (comma 7).`,
    inParoleSemplici: `Istituisce la piattaforma telematica nazionale (gestita da Unioncamere) dove si presenta l'istanza, e disciplina la nomina dell'esperto da parte di una commissione. Sulla piattaforma vivono il test pratico di risanamento e la lista di controllo del decreto attuativo.`,
    esempio: `L'imprenditore compila l'istanza sulla piattaforma, allega bilanci e situazione debitoria, e una commissione nomina un esperto scelto da un elenco di professionisti formati.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art13.html`,
  },
  {
    numero: `16`,
    rubrica: `Requisiti di indipendenza e doveri dell'esperto e delle parti`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. L'esperto deve essere in possesso dei requisiti previsti dall'articolo 2399 del codice civile e non deve essere legato all'impresa o ad altre parti interessate all'operazione di risanamento da rapporti di natura personale o professionale; il professionista ed i soggetti con i quali è eventualmente unito in associazione professionale non devono aver prestato negli ultimi cinque anni attività di lavoro subordinato o autonomo in favore dell'imprenditore né essere stati membri degli organi di amministrazione o controllo dell'impresa né aver posseduto partecipazioni in essa. Chi ha svolto l'incarico di esperto non può intrattenere rapporti professionali con l'imprenditore se non sono decorsi almeno due anni dall'archiviazione della composizione negoziata. L'eventuale attività dell'esperto successiva alla composizione negoziata, derivante dalle trattative e dal loro esito, rientra nell'incarico conferitogli e pertanto non costituisce attività professionale ai sensi del secondo periodo.
2. L'esperto è terzo rispetto a tutte le parti e opera in modo professionale, riservato, imparziale e indipendente. Non è equiparabile al professionista indipendente di cui all'articolo 2, comma 1, lettera o). L'esperto, nell'espletamento dell'incarico di cui all'articolo 12, comma 2, verifica la coerenza complessiva delle informazioni fornite dall'imprenditore chiedendo al medesimo e ai creditori tutte le ulteriori informazioni utili o necessarie. Può avvalersi di soggetti dotati di specifica competenza, anche nel settore economico in cui opera l'imprenditore, e di un revisore legale, non legati all'impresa o ad altre parti interessate all'operazione di risanamento da rapporti di natura personale o professionale.
2-bis. L'esperto dà conto, nei pareri che gli vengono richiesti, dell'attività che ha svolto e che intende svolgere nell'agevolare le trattative tra l'imprenditore, i creditori ed eventuali altri soggetti interessati.
3. Fatto salvo quanto previsto dall'articolo 19, comma 4, l'esperto non può essere tenuto a deporre sul contenuto delle dichiarazioni rese e delle informazioni acquisite nell'esercizio delle sue funzioni, né davanti all'autorità giudiziaria né davanti ad altra autorità. Si applicano le disposizioni dell'articolo 200 del codice di procedura penale e le garanzie previste per il difensore dalle disposizioni dell'articolo 103 del codice di procedura penale in quanto compatibili.
4. L'imprenditore ha il dovere di rappresentare la propria situazione all'esperto, ai creditori e agli altri soggetti interessati in modo completo e trasparente e di gestire il patrimonio e l'impresa senza pregiudicare ingiustamente gli interessi dei creditori.
5. Le banche e gli intermediari finanziari, i mandatari e i cessionari dei loro crediti sono tenuti a partecipare alle trattative in modo attivo e informato. La notizia dell'accesso alla composizione negoziata della crisi e il coinvolgimento nelle trattative non costituiscono di per sé causa di sospensione e di revoca delle linee di credito concesse all'imprenditore né ragione di una diversa classificazione del credito. Nel corso della composizione negoziata la classificazione del credito viene determinata tenuto conto di quanto previsto dal progetto di piano rappresentato ai creditori e della disciplina di vigilanza prudenziale, senza che rilevi il solo fatto che l'imprenditore abbia fatto accesso alla composizione negoziata. L'eventuale sospensione o revoca delle linee di credito determinate dalla applicazione della disciplina di vigilanza prudenziale deve essere comunicata agli organi di amministrazione e controllo dell'impresa, dando conto delle ragioni specifiche della decisione assunta. La prosecuzione del rapporto non è di per sé motivo di responsabilità della banca e dell'intermediario finanziario.
6. Tutte le parti coinvolte nelle trattative hanno il dovere di collaborare lealmente e in modo sollecito con l'imprenditore e con l'esperto e rispettano l'obbligo di riservatezza sulla situazione dell'imprenditore, sulle iniziative da questi assunte o programmate e sulle informazioni acquisite nel corso delle trattative. Le medesime parti danno riscontro alle proposte e alle richieste che ricevono durante le trattative con risposta tempestiva e motivata.`,
    soglie: `Indipendenza (comma 1): assenza di attività di lavoro subordinato/autonomo in favore dell'imprenditore negli ultimi 5 anni; divieto di rapporti professionali con l'imprenditore per almeno 2 anni dall'archiviazione della composizione negoziata.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art16.html`,
  },
  {
    numero: `17`,
    rubrica: `Accesso alla composizione negoziata e suo funzionamento`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. L'istanza di nomina dell'esperto indipendente è presentata tramite la piattaforma telematica di cui all'articolo 13 mediante la compilazione di un modello, ivi disponibile, contenente le informazioni utili ai fini della nomina e dello svolgimento dell'incarico da parte dell'esperto nominato.
2. Il contenuto del modello di cui al comma 1 è definito con il decreto dirigenziale del Ministero della giustizia di cui all'articolo 13, comma 2.
3. L'imprenditore, al momento della presentazione dell'istanza, inserisce nella piattaforma telematica: a) i bilanci approvati degli ultimi tre esercizi, se non già depositati presso l'ufficio del registro delle imprese, oppure, per gli imprenditori che non sono tenuti al deposito dei bilanci, le dichiarazioni dei redditi e dell'IVA degli ultimi tre periodi di imposta, nonché una situazione economico-patrimoniale e finanziaria aggiornata a non oltre sessanta giorni prima della presentazione dell'istanza; a-bis) in caso di mancata approvazione dei bilanci, i progetti di bilancio o una situazione economico-patrimoniale e finanziaria aggiornata a non oltre sessanta giorni prima della presentazione dell'istanza; b) un progetto di piano di risanamento redatto secondo le indicazioni della lista di controllo di cui all'articolo 13, comma 2, e una relazione chiara e sintetica sull'attività in concreto esercitata recante un piano finanziario per i successivi sei mesi e le iniziative che intende adottare; c) l'elenco dei creditori, con l'indicazione dei rispettivi crediti scaduti e a scadere e dell'esistenza di diritti reali e personali di garanzia; d) una dichiarazione resa ai sensi dell'articolo 46 del testo unico di cui al d.P.R. n. 445 del 2000 sulla pendenza, nei suoi confronti, di ricorsi per l'apertura della liquidazione giudiziale o per l'accertamento dello stato di insolvenza e una dichiarazione con la quale attesta di non avere depositato domanda di accesso agli strumenti di regolazione della crisi o dell'insolvenza, anche nelle ipotesi di cui agli articoli 44, comma 1, lettera a), e 74 o con ricorso depositato ai sensi dell'articolo 54, comma 3; e) il certificato unico dei debiti tributari di cui all'articolo 364, comma 1; f) la situazione debitoria complessiva richiesta all'Agenzia delle entrate-Riscossione; g) il certificato dei debiti contributivi e per premi assicurativi di cui all'articolo 363, comma 1; h) un estratto delle informazioni presenti nella Centrale dei rischi gestita dalla Banca d'Italia non anteriore di tre mesi rispetto alla presentazione dell'istanza.
3-bis. Nelle more del rilascio delle certificazioni previste dal comma 3, lettere e), f) e g), l'imprenditore può inserire nella piattaforma una dichiarazione resa ai sensi dell'articolo 46 del d.P.R. n. 445 del 2000 con la quale attesta di avere richiesto, almeno dieci giorni prima della presentazione dell'istanza di nomina dell'esperto, le certificazioni medesime.
4. L'esperto, verificati la propria indipendenza e il possesso delle competenze e della disponibilità di tempo necessarie per lo svolgimento dell'incarico, entro due giorni lavorativi dalla ricezione della nomina, comunica all'imprenditore l'accettazione e contestualmente inserisce nella piattaforma la dichiarazione di accettazione e una dichiarazione resa ai sensi dell'articolo 47 del d.P.R. n. 445 del 2000, sul possesso dei requisiti di indipendenza di cui all'articolo 16, comma 1. In caso contrario ne dà comunicazione riservata al soggetto che l'ha nominato perché provveda alla sua sostituzione. L'esperto non può assumere più di due incarichi contemporaneamente.
5. L'esperto, accettato l'incarico, convoca senza indugio l'imprenditore per valutare l'esistenza di una concreta prospettiva di risanamento, anche alla luce delle informazioni assunte dall'organo di controllo e dal revisore legale, ove in carica. L'imprenditore partecipa personalmente, può farsi assistere da consulenti e informa l'esperto sullo stato delle trattative che conduce senza la sua presenza. Se ritiene che le prospettive di risanamento sono concrete l'esperto incontra le altre parti interessate al processo di risanamento e prospetta le possibili strategie di intervento fissando i successivi incontri con cadenza periodica ravvicinata. Se non ravvisa concrete prospettive di risanamento, all'esito della convocazione o in un momento successivo, l'esperto ne dà notizia all'imprenditore e al segretario generale della camera di commercio che dispone l'archiviazione dell'istanza di composizione negoziata entro i successivi cinque giorni lavorativi. Nel corso delle trattative l'esperto può invitare le parti a rideterminare, secondo buona fede, il contenuto dei contratti ad esecuzione continuata o periodica ovvero ad esecuzione differita se la prestazione è divenuta eccessivamente onerosa o se è alterato l'equilibrio del rapporto in ragione di circostanze sopravvenute. Le parti sono tenute a collaborare tra loro per rideterminare il contenuto del contratto o adeguare le prestazioni alle mutate condizioni.
6. Entro tre giorni dalla comunicazione della convocazione le parti possono presentare osservazioni sull'indipendenza dell'esperto al segretario generale della camera di commercio il quale riferisce senza indugio alla commissione perché, valutate le circostanze esposte e sentito l'esperto, se lo ritiene opportuno provveda alla sua sostituzione entro i successivi cinque giorni lavorativi. Allo stesso modo la commissione procede se l'imprenditore e due o più parti interessate formulano osservazioni sull'operato dell'esperto.
7. L'incarico dell'esperto si considera concluso se, decorsi centottanta giorni dalla accettazione della nomina, le parti non hanno individuato, anche a seguito di sua proposta, una soluzione adeguata per il superamento delle condizioni di cui all'articolo 12, comma 1. Fermo quanto previsto dal comma 5, quarto periodo, l'incarico può proseguire per non oltre centottanta giorni quando lo richiedono l'imprenditore o le parti con le quali sono in corso le trattative e l'esperto vi acconsente, oppure quando l'imprenditore ha fatto ricorso al tribunale ai sensi degli articoli 19 e 22 oppure pendono le misure protettive o cautelari o è necessario attuare il provvedimento di autorizzazione concesso dal tribunale. La prosecuzione dell'incarico è inserita nella piattaforma a cura dell'esperto, il quale ne dà comunicazione alle parti con le quali sono in corso le trattative e, in caso di concessione delle misure protettive e cautelari di cui agli articoli 18 e 19, al giudice che le ha emesse. In caso di sostituzione dell'esperto o nell'ipotesi di cui all'articolo 25, comma 7, il termine di cui al primo periodo decorre dall'accettazione del primo esperto nominato.
8. Al termine dell'incarico l'esperto redige una relazione finale, avente il contenuto previsto dal decreto dirigenziale di cui all'articolo 13, comma 2, che inserisce nella piattaforma e comunica all'imprenditore, a coloro che hanno partecipato alle trattative e, in caso di concessione delle misure protettive e cautelari di cui agli articoli 18 e 19, al giudice che le ha emesse, il quale ne dichiara cessati gli effetti. Eseguiti gli adempimenti di cui al primo periodo, l'esperto ne dà comunicazione al segretario generale della camera di commercio per l'archiviazione dell'istanza di composizione negoziata. L'archiviazione è iscritta nel registro delle imprese in presenza di una istanza di applicazione delle misure protettive e cautelari pubblicata nel medesimo registro.
9. In caso di archiviazione dell'istanza di cui al comma 1, l'imprenditore non può presentare una nuova istanza prima di un anno dall'archiviazione. Se l'archiviazione è richiesta dall'imprenditore con istanza depositata con le modalità previste nel comma 1 entro due mesi dall'accettazione dell'esperto, il termine di cui al primo periodo è ridotto, per una sola volta, a quattro mesi.
10. Ai costi che gravano sulle camere di commercio per consentire il funzionamento della procedura di composizione negoziata per la soluzione della crisi d'impresa si provvede mediante il versamento, a carico dell'impresa che propone l'istanza, di diritti di segreteria determinati ai sensi dell'articolo 18 della legge 29 dicembre 1993, n. 580.`,
    soglie: `Situazione economico-patrimoniale aggiornata a non oltre 60 giorni prima dell'istanza; piano finanziario per i successivi 6 mesi; estratto Centrale dei rischi non anteriore a 3 mesi; certificazioni richieste almeno 10 giorni prima dell'istanza (comma 3-bis); accettazione dell'esperto entro 2 giorni lavorativi; massimo 2 incarichi contemporanei; archiviazione entro 5 giorni lavorativi; osservazioni sull'indipendenza entro 3 giorni, sostituzione entro 5 giorni lavorativi; durata incarico 180 giorni, prorogabile per non oltre altri 180 giorni; nuova istanza non prima di 1 anno dall'archiviazione, ridotto per una sola volta a 4 mesi se l'archiviazione è richiesta dall'imprenditore entro 2 mesi dall'accettazione dell'esperto.`,
    inParoleSemplici: `Spiega come si accede concretamente e come funziona il percorso: documenti da allegare, accettazione dell'esperto, durata delle trattative e possibilità di proroga. È la «procedura» operativa della composizione negoziata.`,
    esempio: `All'istanza si allegano bilanci degli ultimi tre esercizi, elenco dei creditori, situazione debitoria complessiva (comprese le posizioni verso enti come INPS e Agenzia delle Entrate) e un progetto di piano.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art17.html`,
  },
  {
    numero: `18`,
    rubrica: `Misure protettive`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. L'imprenditore può chiedere, con l'istanza di nomina dell'esperto o con successiva istanza presentata con le modalità di cui all'articolo 17, comma 1, l'applicazione di misure protettive del patrimonio nei confronti di tutti i creditori oppure nei confronti di determinate iniziative intraprese dai creditori a tutela dei propri diritti, di determinati creditori o di determinate categorie di creditori. Sono esclusi dalle misure protettive i diritti di credito dei lavoratori. L'istanza di applicazione delle misure protettive è pubblicata nel registro delle imprese unitamente all'accettazione dell'esperto.
2. Con l'istanza di cui al comma 1, l'imprenditore inserisce nella piattaforma telematica una dichiarazione sull'esistenza di misure esecutive o cautelari disposte nei suoi confronti e un aggiornamento sui ricorsi indicati nella dichiarazione resa ai sensi dell'articolo 17, comma 3, lettera d).
3. Dal giorno della pubblicazione dell'istanza di cui al comma 1, i creditori interessati non possono acquisire diritti di prelazione se non concordati con l'imprenditore né possono iniziare o proseguire azioni esecutive e cautelari sul suo patrimonio o sui beni e sui diritti con i quali viene esercitata l'attività d'impresa. Dalla stessa data le prescrizioni rimangono sospese e le decadenze non si verificano. Non sono inibiti i pagamenti.
4. Dal giorno della pubblicazione dell'istanza di cui al comma 1 e fino alla conclusione delle trattative o all'archiviazione dell'istanza di composizione negoziata, la sentenza di apertura della liquidazione giudiziale o di accertamento dello stato di insolvenza non può essere pronunciata, salvo che il tribunale disponga la revoca delle misure protettive. Restano fermi i provvedimenti già concessi ai sensi dell'articolo 54, comma 1.
5. I creditori, ivi compresi le banche e gli intermediari finanziari, i loro mandatari e i cessionari dei loro crediti, nei cui confronti operano le misure protettive non possono, unilateralmente, rifiutare l'adempimento dei contratti pendenti, provocarne la risoluzione, anticiparne la scadenza o modificarli in danno dell'imprenditore oppure revocare in tutto o in parte le linee di credito già concesse per il solo fatto del mancato pagamento di crediti anteriori rispetto alla pubblicazione dell'istanza di cui al comma 1. I medesimi creditori possono sospendere l'adempimento dei contratti pendenti dalla pubblicazione dell'istanza di cui al comma 1 fino alla conferma delle misure richieste. Restano ferme in ogni caso la sospensione e la revoca delle linee di credito disposte per effetto dell'applicazione della disciplina di vigilanza prudenziale. La prosecuzione del rapporto non è di per sé motivo di responsabilità della banca o dell'intermediario finanziario.
5-bis. Dal momento della conferma delle misure protettive, le banche e gli intermediari finanziari, i mandatari e i cessionari dei loro crediti nei cui confronti le misure sono state confermate non possono mantenere la sospensione relativa alle linee di credito accordate al momento dell'accesso alla composizione negoziata se non dimostrano che la sospensione è determinata dalla applicazione della disciplina di vigilanza prudenziale. La prosecuzione del rapporto non è di per sé motivo di responsabilità della banca o dell'intermediario finanziario.`,
    soglie: `Le misure operano dal giorno della pubblicazione dell'istanza nel registro delle imprese. (Le soglie temporali sulla durata/conferma sono disciplinate dall'art. 19.)`,
    inParoleSemplici: `Consente all'imprenditore di chiedere misure protettive: un «ombrello» temporaneo che blocca o congela le azioni esecutive e cautelari dei creditori mentre le trattative sono in corso, così da non far saltare il risanamento sul più bello.`,
    esempio: `Con le misure protettive pubblicate nel registro delle imprese, un fornitore non può iscrivere ipoteca né avviare un pignoramento per i crediti anteriori finché durano le trattative.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art18.html`,
  },
  {
    numero: `19`,
    rubrica: `Procedimento relativo alle misure protettive e cautelari`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. Quando l'imprenditore formula la richiesta di cui all'articolo 18, comma 1, con ricorso presentato al tribunale competente ai sensi dell'articolo 27, entro il giorno successivo alla pubblicazione dell'istanza e dell'accettazione dell'esperto, chiede la conferma o la modifica delle misure protettive e, ove occorre, l'adozione dei provvedimenti cautelari necessari per condurre a termine le trattative. Entro venti giorni dalla pubblicazione di cui al medesimo articolo 18, comma 1, l'imprenditore chiede la pubblicazione nel registro delle imprese del numero di ruolo generale del procedimento instaurato. L'omesso o il ritardato deposito del ricorso è causa di inefficacia delle misure previste dall'articolo 18, comma 1, e, decorso inutilmente il termine di cui al secondo periodo, l'iscrizione dell'istanza è cancellata dal registro delle imprese.
2. L'imprenditore, unitamente al ricorso, deposita: a) i bilanci approvati degli ultimi tre esercizi oppure, quando non è tenuto al deposito dei bilanci, le dichiarazioni dei redditi e dell'IVA degli ultimi tre periodi di imposta; a-bis) in caso di mancata approvazione dei bilanci, i progetti di bilancio o una situazione economico-patrimoniale e finanziaria aggiornata a non oltre sessanta giorni prima della presentazione della domanda; b) una situazione economico-patrimoniale e finanziaria aggiornata a non oltre sessanta giorni prima del deposito del ricorso; c) l'elenco dei creditori, individuando i primi dieci per ammontare, con indicazione dei relativi indirizzi di posta elettronica certificata, se disponibili, oppure degli indirizzi di posta elettronica non certificata per i quali sia verificata o verificabile la titolarità della singola casella; d) un progetto di piano di risanamento redatto secondo le indicazioni della lista di controllo di cui all'articolo 13, comma 2, un piano finanziario per i successivi sei mesi e un prospetto delle iniziative che intende adottare; e) una dichiarazione avente valore di autocertificazione attestante, sulla base di criteri di ragionevolezza e proporzionalità, che l'impresa può essere risanata; f) l'accettazione dell'esperto nominato ai sensi dell'articolo 13, commi 6, 7 e 8, con il relativo indirizzo di posta elettronica certificata.
3. Il tribunale, entro dieci giorni dal deposito del ricorso, fissa con decreto l'udienza, da tenersi preferibilmente con sistemi di videoconferenza. Entro il giorno successivo al deposito in cancelleria il decreto è trasmesso per estratto, a cura del cancelliere, all'ufficio del registro delle imprese ai fini della sua iscrizione, da effettuarsi entro il giorno successivo. L'estratto contiene l'indicazione del debitore e dell'esperto e la data dell'udienza. Il ricorso, unitamente al decreto, è notificato dal ricorrente, anche all'esperto. Il tribunale può prescrivere ai sensi dell'articolo 151 del codice di procedura civile, le forme di notificazione opportune per garantire la celerità del procedimento, indicandone i destinatari, e, tenuto conto della pubblicazione del decreto prevista dal secondo periodo, può dettare le ulteriori disposizioni ritenute utili per assicurare la conoscenza del procedimento. Se il ricorso non è depositato nel termine previsto dal comma 1, il tribunale dichiara con decreto motivato l'inefficacia delle misure protettive, senza fissare l'udienza prevista dal primo periodo. Gli effetti protettivi prodotti ai sensi dell'articolo 18, comma 1, cessano altresì se, nel termine di cui al primo periodo, il giudice non provvede alla fissazione dell'udienza. Nei casi previsti dal sesto e settimo periodo la domanda può essere riproposta.
4. All'udienza il tribunale, sentite le parti e chiamato l'esperto a esprimere il proprio parere sulla funzionalità delle misure richieste ad assicurare il buon esito delle trattative e a rappresentare l'attività che intende svolgere ai sensi dell'articolo 12, comma 2, omessa ogni formalità non essenziale al contraddittorio, nomina, se occorre, un ausiliario ai sensi dell'articolo 68 del codice di procedura civile e procede agli atti di istruzione indispensabili in relazione ai provvedimenti cautelari richiesti ai sensi del comma 1 e ai provvedimenti di conferma, revoca o modifica delle misure protettive. Il tribunale può assumere informazioni dai creditori indicati nell'elenco di cui al comma 2, lettera c). Se le misure protettive o i provvedimenti cautelari richiesti incidono sui diritti dei terzi, devono essere sentiti. Il tribunale provvede con ordinanza con la quale stabilisce la durata, non inferiore a trenta e non superiore a centoventi giorni, delle misure protettive e, se occorre, dei provvedimenti cautelari disposti, tenendo conto delle misure eventualmente già concesse ai sensi dell'articolo 54, comma 1. Sentito l'esperto, il tribunale può limitare le misure a determinate iniziative intraprese dai creditori a tutela dei propri diritti o a determinati creditori o categorie di creditori.
5. Il giudice che ha emesso i provvedimenti di cui al comma 4, su istanza del debitore o delle parti interessate all'operazione di risanamento, può prorogare la durata delle misure disposte per il tempo necessario ad assicurare il buon esito delle trattative, acquisito il parere dell'esperto. Nel parere l'esperto indica altresì l'attività svolta e da svolgere ai sensi dell'articolo 12, comma 2. La proroga non è concessa se il centro degli interessi principali dell'impresa è stato trasferito da un altro Stato membro nei tre mesi precedenti alla formulazione della richiesta di cui all'articolo 18, comma 1. La durata complessiva delle misure non può superare i duecentoquaranta giorni.
6. Su istanza dell'imprenditore, di uno o più creditori o su segnalazione dell'esperto, il giudice che ha emesso i provvedimenti di cui al comma 4 o 5 può, in qualunque momento, sentite le parti interessate, e in ogni caso a seguito dell'archiviazione dell'istanza ai sensi dell'articolo 17, commi 5 e 8, revocare le misure protettive e cautelari, o abbreviarne la durata, quando esse non soddisfano l'obiettivo di assicurare il buon esito delle trattative o appaiono sproporzionate rispetto al pregiudizio arrecato ai creditori istanti.
7. I procedimenti disciplinati dal presente articolo si svolgono nella forma prevista dagli articoli 669-bis e seguenti del codice di procedura civile e il tribunale provvede in composizione monocratica con ordinanza comunicata dalla cancelleria al registro delle imprese entro il giorno successivo. Non si applicano l'articolo 669-octies, primo, secondo e terzo comma, e l'articolo 669-novies, primo comma, del codice di procedura civile. Contro l'ordinanza è ammesso reclamo ai sensi dell'articolo 669-terdecies del codice di procedura civile.
8. In caso di revoca o cessazione delle misure protettive, il divieto di acquisire diritti di prelazione se non concordati con l'imprenditore viene meno a far data dalla revoca o dalla cessazione delle misure protettive.`,
    soglie: `Ricorso al tribunale entro il giorno successivo alla pubblicazione dell'istanza; pubblicazione del n. di ruolo entro 20 giorni; fissazione udienza entro 10 giorni dal deposito; situazioni contabili aggiornate a non oltre 60 giorni; durata delle misure protettive stabilita dal tribunale NON inferiore a 30 e NON superiore a 120 giorni; proroga esclusa se il COMI è stato trasferito da altro Stato membro nei 3 mesi precedenti; durata complessiva delle misure NON superiore a 240 giorni.`,
    inParoleSemplici: `È il procedimento davanti al tribunale per confermare (o revocare) le misure protettive e per eventuali misure cautelari. Fissa tempi stretti e il contraddittorio con i creditori.`,
    esempio: `Entro pochi giorni dalla pubblicazione, l'imprenditore deposita il ricorso e il tribunale fissa l'udienza per confermare l'ombrello protettivo.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art19.html`,
  },
  {
    numero: `21`,
    rubrica: `Gestione dell'impresa in pendenza delle trattative`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. Nel corso delle trattative l'imprenditore conserva la gestione ordinaria e straordinaria dell'impresa. L'imprenditore in stato di crisi gestisce l'impresa e individua la soluzione per il superamento della situazione di insolvenza in modo da evitare pregiudizio alla sostenibilità economico-finanziaria dell'attività. Quando, nel corso della composizione negoziata, risulta che l'imprenditore è insolvente ma esistono concrete prospettive di risanamento, lo stesso gestisce l'impresa nel prevalente interesse dei creditori. Restano ferme le responsabilità dell'imprenditore.
2. L'imprenditore informa preventivamente l'esperto, per iscritto, del compimento di atti di straordinaria amministrazione nonché dell'esecuzione di pagamenti che non sono coerenti rispetto alle trattative o alle prospettive di risanamento.
3. L'esperto, quando ritiene che l'atto può arrecare pregiudizio ai creditori, alle trattative o alle prospettive di risanamento, lo segnala per iscritto all'imprenditore e all'organo di controllo.
4. Se, nonostante la segnalazione, l'atto viene compiuto, l'imprenditore ne informa immediatamente l'esperto il quale, nei successivi dieci giorni, può iscrivere il proprio dissenso nel registro delle imprese. Quando l'atto compiuto pregiudica gli interessi dei creditori, l'iscrizione è obbligatoria.
5. Quando sono state concesse misure protettive o cautelari l'esperto, iscritto il proprio dissenso nel registro delle imprese, procede alla segnalazione di cui all'articolo 19, comma 6.`,
    soglie: `L'esperto può iscrivere il proprio dissenso nel registro delle imprese nei 10 giorni successivi (comma 4).`,
    inParoleSemplici: `Detta le regole di condotta dell'imprenditore mentre tratta: continua a gestire l'impresa (anche gli atti di straordinaria amministrazione), ma deve evitare di pregiudicare ingiustamente i creditori e informare l'esperto sugli atti rilevanti.`,
    esempio: `Prima di vendere un capannone durante le trattative, l'imprenditore ne informa l'esperto, che può segnalare per iscritto il proprio dissenso se l'operazione danneggia i creditori.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art21.html`,
  },
  {
    numero: `23`,
    rubrica: `Conclusione delle trattative`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. Quando è individuata una soluzione idonea al superamento della situazione di cui all'articolo 12, comma 1, le parti possono, alternativamente: a) concludere un contratto, con uno o più creditori oppure con una o più parti interessate all'operazione di risanamento, che produce gli effetti di cui all'articolo 25-bis, comma 1, se, secondo la relazione dell'esperto di cui all'articolo 17, comma 8, è idoneo ad assicurare la continuità aziendale per un periodo non inferiore a due anni; b) concludere la convenzione di moratoria di cui all'articolo 62; c) concludere un accordo sottoscritto dall'imprenditore, dai creditori aderenti e dalle altre parti interessate all'operazione di risanamento che vi hanno aderito nonché dall'esperto che produce gli effetti di cui agli articoli 166, comma 3, lettera d), e 324. Con la sottoscrizione dell'accordo l'esperto dà atto che il piano di risanamento appare coerente con la regolazione della crisi o dell'insolvenza.
2. Oltre ai contratti o agli accordi di cui al comma 1, l'imprenditore può anche, alternativamente: a) predisporre il piano attestato di risanamento di cui all'articolo 56; b) chiedere l'omologazione di un accordo di ristrutturazione dei debiti ai sensi degli articoli 57, 60 e 61. La percentuale di cui all'articolo 61, comma 2, lettera c), è ridotta al 60 per cento se il raggiungimento dell'accordo risulta dalla relazione finale dell'esperto o se la domanda di omologazione è proposta nei sessanta giorni successivi alla comunicazione di cui all'articolo 17, comma 8; c) proporre la domanda di concordato semplificato per la liquidazione del patrimonio di cui all'articolo 25-sexies; d) accedere ad uno degli strumenti di regolazione della crisi e dell'insolvenza disciplinati dal presente codice, dal decreto legislativo 8 luglio 1999, n. 270 o dal decreto-legge 23 dicembre 2003, n. 347, convertito, con modificazioni, dalla legge 18 febbraio 2004, n. 39. L'imprenditore agricolo può accedere agli strumenti di cui all'articolo 25-quater, comma 4.
2-bis. Nel corso delle trattative l'imprenditore può formulare una proposta di accordo transattivo alle agenzie fiscali, all'Agenzia delle entrate-Riscossione che prevede il pagamento, parziale o dilazionato, del debito e dei relativi accessori. La proposta non può essere formulata in relazione ai tributi costituenti risorse proprie dell'Unione europea. Alla proposta sono allegate la relazione di un professionista indipendente che ne attesta la convenienza rispetto all'alternativa della liquidazione giudiziale per il creditore pubblico cui la proposta è rivolta e una relazione sulla completezza e veridicità dei dati aziendali redatta dal soggetto incaricato della revisione legale, se esistente, o da un revisore legale iscritto nell'apposito registro a tal fine designato. L'accordo è sottoscritto dalle parti e comunicato all'esperto e produce effetti con il suo deposito presso il tribunale competente ai sensi dell'articolo 27. Per i tributi amministrati dall'Agenzia delle entrate, l'accordo è sottoscritto dal Direttore dell'ufficio su parere conforme della competente Direzione regionale. Per i tributi amministrati dall'Agenzia delle dogane e dei monopoli l'accordo è sottoscritto dal Direttore delle Direzioni territoriali, dal Direttore della Direzione territoriale interprovinciale e, per gli atti impositivi emessi dagli uffici delle Direzioni centrali, dal Direttore delle medesime Direzioni centrali. Il giudice, verificata la regolarità della documentazione allegata e dell'accordo, ne autorizza l'esecuzione con decreto o, in alternativa, dichiara che l'accordo è privo di effetti. L'accordo si risolve di diritto in caso di apertura della liquidazione giudiziale o della liquidazione controllata o di accertamento dello stato di insolvenza oppure se l'imprenditore non esegue integralmente, entro sessanta giorni dalle scadenze previste, i pagamenti dovuti.
2-ter. Le soluzioni di cui ai commi 1 e 2 possono intervenire durante le trattative o a conclusione della composizione negoziata e la sottoscrizione dell'esperto, quando prevista, può essere apposta successivamente.`,
    soglie: `Contratto ex comma 1 lett. a): idoneo ad assicurare la continuità aziendale per un periodo NON inferiore a 2 anni. Comma 2 lett. b): percentuale ex art. 61, c.2, lett. c) ridotta al 60% se l'accordo risulta dalla relazione finale dell'esperto o se l'omologazione è proposta entro 60 giorni dalla comunicazione ex art. 17, c.8. Comma 2-bis: accordo transattivo fiscale risolto di diritto se i pagamenti non sono eseguiti integralmente entro 60 giorni dalle scadenze; esclusi i tributi costituenti risorse proprie UE.`,
    inParoleSemplici: `Elenca i possibili esiti delle trattative: dal contratto con uno o più creditori, all'accordo assistito dall'esperto, fino all'accesso a uno strumento di regolazione della crisi (accordi di ristrutturazione, concordato, o il concordato semplificato se le trattative non riescono ma sono state condotte correttamente).`,
    esempio: `Se le trattative vanno a buon fine, l'impresa firma un accordo di ristrutturazione dei debiti con le banche; se falliscono nonostante l'impegno, può accedere al concordato semplificato.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art23.html`,
  },
  {
    numero: `25-bis`,
    rubrica: `Misure premiali`,
    capo: `Parte Prima - Titolo II - Capo I`,
    testo: `1. Dall'accettazione dell'incarico da parte dell'esperto e sino alla conclusione delle trattative con una delle soluzioni previste dall'articolo 23, commi 1 e 2, lettera b), gli interessi che maturano sui debiti tributari dell'imprenditore sono ridotti alla misura legale.
2. Le sanzioni tributarie per le quali è prevista l'applicazione in misura ridotta in caso di pagamento entro un determinato termine dalla comunicazione dell'ufficio che le irroga, sono ridotte alla misura minima se il termine per il pagamento scade dopo la presentazione della istanza di cui all'articolo 17.
3. Le sanzioni e gli interessi sui debiti tributari sorti prima del deposito dell'istanza di cui all'articolo 17 e oggetto della composizione negoziata sono ridotti della metà nelle ipotesi previste dall'articolo 23, comma 2.
4. In caso di pubblicazione nel registro delle imprese del contratto di cui all'articolo 23, comma 1, lettera a), e dell'accordo di cui all'articolo 23, comma 1, lettera c), l'Agenzia delle entrate concede all'imprenditore che lo richiede, con istanza sottoscritta anche dall'esperto, un piano di rateazione fino ad un massimo di settantadue rate mensili delle somme dovute e non versate a titolo di imposte sul reddito, ritenute alla fonte operate in qualità di sostituto d'imposta, imposta sul valore aggiunto e imposta regionale sulle attività produttive non ancora iscritte a ruolo, e relativi accessori. Si applicano, in quanto compatibili, le disposizioni di cui all'articolo 19 del decreto del Presidente della Repubblica 29 settembre 1973, n. 602. La sottoscrizione dell'esperto costituisce prova dell'esistenza della temporanea situazione di obiettiva difficoltà. L'imprenditore decade automaticamente dal beneficio della rateazione anche in caso di successivo deposito di ricorso ai sensi dell'articolo 40 o in caso di apertura della procedura di liquidazione giudiziale o della liquidazione controllata o di accertamento dello stato di insolvenza oppure in caso di mancato pagamento anche di una sola rata alla sua scadenza. Il piano di rateazione di cui al primo periodo può essere concesso dall'Agenzia delle entrate fino a centoventi rate in caso di comprovata e grave situazione di difficoltà dell'impresa rappresentata nell'istanza depositata ai sensi del primo periodo e sottoscritta dall'esperto.
5. Dalla pubblicazione nel registro delle imprese del contratto e dell'accordo di cui all'articolo 23, comma 1, lettere a) e c), o degli accordi di cui all'articolo 23, comma 2, lettera b), si applicano gli articoli 88, comma 4-ter, e 101, comma 5, del testo unico delle imposte sui redditi, di cui al decreto del Presidente della Repubblica 22 dicembre 1986, n. 917. Dalla stessa data si applica l'articolo 26, comma 3-bis, del decreto del Presidente della Repubblica 26 ottobre 1972, n. 633.
6. Nel caso di successiva apertura della procedura di liquidazione giudiziale o di liquidazione controllata o nel caso di accertamento dello stato di insolvenza, gli interessi e le sanzioni sono dovuti senza le riduzioni di cui ai commi 1 e 2.`,
    soglie: `Interessi sui debiti tributari ridotti alla misura LEGALE (comma 1); sanzioni tributarie ridotte alla misura MINIMA (comma 2); sanzioni e interessi (debiti anteriori) ridotti della META' nelle ipotesi dell'art. 23, c.2 (comma 3); piano di rateazione con l'Agenzia delle entrate fino a 72 rate mensili, elevabili fino a 120 rate in caso di comprovata e grave situazione di difficoltà (comma 4); decadenza per mancato pagamento anche di una sola rata.`,
    inParoleSemplici: `Prevede le misure premiali (incentivi) per chi attiva tempestivamente la composizione negoziata: riduzione di interessi e sanzioni sui debiti fiscali, rateizzazioni più ampie e altri benefici, per premiare chi non aspetta troppo.`,
    esempio: `Durante le trattative, gli interessi sui debiti tributari sono ridotti alla misura legale e le sanzioni possono essere abbattute, alleggerendo il peso del risanamento.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-i/art25bis.html`,
  },
  {
    numero: `25-sexies`,
    rubrica: `Concordato semplificato per la liquidazione del patrimonio`,
    capo: `Parte Prima - Titolo II - Capo II`,
    testo: `1. Quando l'esperto nella relazione finale dichiara che le trattative si sono svolte secondo correttezza e buona fede, e che le soluzioni individuate ai sensi dell'articolo 23, commi 1 e 2, lettere a), e b) non sono praticabili, l'imprenditore può presentare, nei sessanta giorni successivi alla comunicazione di cui all'articolo 17, comma 8, una proposta di concordato per cessione dei beni unitamente al piano di liquidazione e ai documenti indicati nell'articolo 39. La proposta può prevedere la suddivisione dei creditori in classi e si applica l'articolo 84, comma 5. Nel rispetto del termine di cui al primo periodo, l'imprenditore può proporre la domanda di cui all'articolo 40 anche con riserva di deposito della proposta e del piano.
2. L'imprenditore chiede l'omologazione del concordato con ricorso presentato al tribunale del luogo in cui l'impresa ha il proprio centro degli interessi principali. Il ricorso è comunicato al pubblico ministero e pubblicato, a cura del cancelliere, nel registro delle imprese entro il giorno successivo alla data del suo deposito. Dalla data della pubblicazione del ricorso si producono gli effetti di cui agli articoli 6, 46, 94 e 96.
3. Il tribunale, acquisiti la relazione finale di cui al comma 1 e il parere dell'esperto con specifico riferimento ai presumibili risultati della liquidazione e alle garanzie offerte e valutata la ritualità della proposta anche con riferimento alla corretta formazione delle classi, nomina un ausiliario ai sensi dell'articolo 68 del codice di procedura civile, assegnando allo stesso un termine per il deposito del parere di cui al comma 4. L'ausiliario fa pervenire l'accettazione dell'incarico entro tre giorni dalla comunicazione. All'ausiliario si applicano le disposizioni di cui agli articoli 35, comma 4-bis, e 35.1 del codice delle leggi antimafia e delle misure di prevenzione, di cui al decreto legislativo 6 settembre 2011, n. 159. Si osservano altresì le disposizioni di cui all'articolo 35.2 del citato decreto legislativo n. 159 del 2011. Il Tribunale può concedere un termine non superiore a quindici giorni per apportare integrazioni e modifiche e produrre nuovi documenti.
4. Con il medesimo decreto ovvero, in caso di concessione del termine di cui al comma 3, con successivo decreto il tribunale ordina che la proposta, unitamente al parere dell'ausiliario e alla relazione finale e al parere dell'esperto, sia comunicata a cura del debitore ai creditori risultanti dall'elenco depositato ai sensi dell'articolo 39, comma 1, ove possibile a mezzo posta elettronica certificata o, in mancanza, a mezzo di raccomandata con avviso di ricevimento, specificando dove possono essere reperiti i dati per la sua valutazione e fissa l'udienza per l'omologazione. Tra la scadenza del termine concesso all'ausiliario ai sensi del comma 3 e l'udienza di omologazione devono decorrere non meno di quarantacinque giorni. I creditori e qualsiasi interessato possono proporre opposizione all'omologazione costituendosi nel termine perentorio di dieci giorni prima dell'udienza fissata.
5. Il tribunale, assunti i mezzi istruttori richiesti dalle parti o disposti d'ufficio, omologa il concordato quando, verificata la regolarità del contraddittorio e del procedimento, nonché il rispetto dell'ordine delle cause di prelazione e la fattibilità del piano di liquidazione, rileva che la proposta non arreca pregiudizio ai creditori rispetto all'alternativa della liquidazione giudiziale o della liquidazione controllata e comunque assicura un'utilità a ciascun creditore.
6. Il tribunale provvede con decreto motivato, immediatamente esecutivo. Il decreto, pubblicato a norma dell'articolo 45 è comunicato dalla cancelleria alle parti che, nei successivi trenta giorni, possono proporre reclamo alla corte di appello ai sensi dell'articolo 247.
7. Contro il decreto della corte d'appello può essere proposto ricorso per cassazione entro trenta giorni dalla comunicazione.
8. Si applicano, in quanto compatibili, le disposizioni di cui agli articoli 106, 117, 118, 119, 324 e 341, sostituita la figura del commissario giudiziale con quella dell'ausiliario. Ai fini di cui all'articolo 106, il decreto di cui al comma 4 equivale all'ammissione al concordato.`,
    soglie: `Proposta di concordato semplificato entro 60 giorni dalla comunicazione della relazione finale (art. 17, c.8); accettazione dell'ausiliario entro 3 giorni; termine per integrazioni/modifiche non superiore a 15 giorni; tra scadenza del termine dell'ausiliario e udienza di omologazione non meno di 45 giorni; opposizione entro il termine perentorio di 10 giorni prima dell'udienza; reclamo alla corte d'appello entro 30 giorni; ricorso per cassazione entro 30 giorni.`,
    inParoleSemplici: `È il concordato semplificato per la liquidazione del patrimonio: una via d'uscita riservata a chi ha condotto le trattative in buona fede ma non ha trovato un accordo. Si propone al tribunale senza voto dei creditori, con particolari garanzie.`,
    esempio: `Falliti i tentativi di accordo pur essendosi comportato correttamente, l'imprenditore propone di liquidare i beni offrendo ai creditori un ricavato non inferiore a quello della liquidazione giudiziale.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-ii/art25sexies.html`,
  },
  {
    numero: `25-octies`,
    rubrica: `Segnalazione dell'organo di controllo e del soggetto incaricato della revisione legale`,
    capo: `Parte Prima - Titolo II - Capo III`,
    testo: `1. L'organo di controllo societario e il soggetto incaricato della revisione legale, nell'esercizio delle rispettive funzioni, segnalano, per iscritto, all'organo amministrativo la sussistenza dei presupposti di cui all'articolo 2, comma 1, lettere a) e b), per la presentazione dell'istanza di cui all'articolo 17. La segnalazione è motivata, è trasmessa con mezzi che assicurano la prova dell'avvenuta ricezione e contiene la fissazione di un congruo termine, non superiore a trenta giorni, entro il quale l'organo amministrativo deve riferire in ordine alle iniziative intraprese. In pendenza delle trattative, rimane fermo il dovere di vigilanza di cui all'articolo 2403 del codice civile.
2. La tempestiva segnalazione all'organo amministrativo ai sensi del comma 1 e la vigilanza sull'andamento delle trattative sono valutate ai fini dell'attenuazione o esclusione della responsabilità prevista dall'articolo 2407 del codice civile o dall'articolo 15 del decreto legislativo 27 gennaio 2010, n. 39. La segnalazione è in ogni caso considerata tempestiva se interviene nel termine di sessanta giorni dalla conoscenza delle condizioni di cui all'articolo 2, comma 1, lettera a), da parte dell'organo di controllo o di revisione.`,
    soglie: `Termine assegnato all'organo amministrativo per riferire: congruo e comunque NON superiore a 30 giorni (comma 1). Segnalazione considerata tempestiva se interviene entro 60 giorni dalla conoscenza delle condizioni di cui all'art. 2, c.1, lett. a) (comma 2).`,
    inParoleSemplici: `Impone all'organo di controllo (es. collegio sindacale) di segnalare per iscritto all'amministratore l'esistenza dei presupposti per la composizione negoziata. È un allarme «interno» che si affianca alle segnalazioni esterne dei creditori pubblici.`,
    esempio: `Il collegio sindacale che rileva squilibri rilevanti scrive all'amministratore invitandolo a valutare l'accesso alla composizione negoziata: la segnalazione tempestiva rileva anche ai fini della responsabilità.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-iii/art25octies.html`,
  },
  {
    numero: `25-novies`,
    rubrica: `Segnalazioni dei creditori pubblici qualificati`,
    capo: `Parte Prima - Titolo II - Capo III`,
    testo: `1. L'Istituto nazionale della previdenza sociale, l'Istituto nazionale per l'assicurazione contro gli infortuni sul lavoro, l'Agenzia delle entrate e l'Agenzia delle entrate-Riscossione segnalano all'imprenditore e, ove esistente, all'organo di controllo, nella persona del presidente del collegio sindacale in caso di organo collegiale, a mezzo di posta elettronica certificata o, in mancanza, mediante raccomandata con avviso di ricevimento inviata all'indirizzo risultante dall'anagrafe tributaria:
a) per l'Istituto nazionale della previdenza sociale, il ritardo di oltre novanta giorni nel versamento di contributi previdenziali di ammontare superiore: 1) per le imprese con lavoratori subordinati e parasubordinati, al 30 per cento di quelli dovuti nell'anno precedente e all'importo di euro 15.000; 2) per le imprese senza lavoratori subordinati e parasubordinati, all'importo di euro 5.000;
b) per l'Istituto nazionale per l'assicurazione contro gli infortuni sul lavoro, l'esistenza di un debito per premi assicurativi scaduto da oltre novanta giorni e non versato superiore all'importo di euro 5.000;
c) per l'Agenzia delle entrate, l'esistenza di un debito scaduto e non versato relativo all'imposta sul valore aggiunto, risultante dalla comunicazione dei dati delle liquidazioni periodiche di cui all'articolo 21-bis del decreto-legge 31 maggio 2010, n. 78, convertito, con modificazioni, dalla legge 30 luglio 2010, n. 122, di importo superiore a euro 5.000 e, comunque, non inferiore al 10 per cento dell'ammontare del volume d'affari risultante dalla dichiarazione relativa all'anno d'imposta precedente; la segnalazione è in ogni caso inviata se il debito è superiore all'importo di euro 20.000;
d) per l'Agenzia delle entrate-Riscossione, l'esistenza di crediti affidati per la riscossione, autodichiarati o definitivamente accertati e scaduti da oltre novanta giorni, superiori, per le imprese individuali, all'importo di euro 100.000, per le società di persone, all'importo di euro 200.000 e, per le altre società, all'importo di euro 500.000.
2. Le segnalazioni di cui al comma 1 sono inviate: a) dall'Agenzia delle entrate, contestualmente alla comunicazione di irregolarità di cui all'articolo 54-bis del decreto del Presidente della Repubblica 26 ottobre 1972, n. 633, e, comunque, non oltre centocinquanta giorni dal termine di presentazione delle comunicazioni di cui all'articolo 21-bis del decreto-legge n. 78 del 2010; b) dall'Istituto nazionale della previdenza sociale, dall'Istituto nazionale per l'assicurazione contro gli infortuni sul lavoro e dall'Agenzia delle entrate-Riscossione, entro sessanta giorni decorrenti dal verificarsi delle condizioni o dal superamento degli importi indicati nel medesimo comma 1.
3. Le segnalazioni di cui al comma 1 contengono l'invito alla presentazione dell'istanza di cui all'articolo 17, comma 1, se ne ricorrono i presupposti.
4. Le disposizioni del presente articolo si applicano: a) con riferimento all'Istituto nazionale della previdenza sociale e all'Istituto nazionale per l'assicurazione contro gli infortuni sul lavoro, in relazione ai debiti accertati a decorrere dal 1° gennaio 2022, per il primo, e ai debiti accertati a decorrere dall'entrata in vigore del presente decreto per il secondo; b) con riferimento all'Agenzia delle entrate, in relazione ai debiti risultanti dalle comunicazioni di cui all'articolo 21-bis del decreto-legge n. 78 del 2010 a decorrere da quelle relative al secondo trimestre 2022; c) con riferimento all'Agenzia delle entrate-Riscossione, in relazione ai carichi affidati all'agente della riscossione a decorrere dal 1° luglio 2022.`,
    soglie: `SOGLIE DI SEGNALAZIONE (comma 1): INPS - ritardo di oltre 90 giorni nel versamento di contributi previdenziali di ammontare superiore: (1) imprese CON lavoratori subordinati/parasubordinati: al 30% di quelli dovuti nell'anno precedente E all'importo di euro 15.000; (2) imprese SENZA lavoratori subordinati/parasubordinati: euro 5.000. INAIL - debito per premi assicurativi scaduto da oltre 90 giorni e non versato superiore a euro 5.000. AGENZIA ENTRATE (IVA) - debito IVA da liquidazioni periodiche (art. 21-bis DL 78/2010) di importo superiore a euro 5.000 e comunque non inferiore al 10% del volume d'affari dell'anno precedente; segnalazione in ogni caso se il debito supera euro 20.000. AGENZIA ENTRATE-RISCOSSIONE - crediti affidati, autodichiarati o definitivamente accertati e scaduti da oltre 90 giorni, superiori a: euro 100.000 (imprese individuali), euro 200.000 (società di persone), euro 500.000 (altre società). TERMINI DI INVIO (comma 2): Agenzia Entrate - contestualmente alla comunicazione di irregolarità ex art. 54-bis DPR 633/1972 e comunque non oltre 150 giorni dal termine di presentazione delle comunicazioni ex art. 21-bis DL 78/2010; INPS, INAIL e Agenzia Entrate-Riscossione - entro 60 giorni dal verificarsi delle condizioni o dal superamento degli importi. DECORRENZE (comma 4): INPS debiti dal 1° gennaio 2022; INAIL debiti dall'entrata in vigore del decreto; Agenzia Entrate comunicazioni dal secondo trimestre 2022; Agenzia Entrate-Riscossione carichi affidati dal 1° luglio 2022.`,
    inParoleSemplici: `È la norma che riguarda direttamente gli enti creditori pubblici — INPS, INAIL, Agenzia delle Entrate e Agenzia Entrate-Riscossione: quando i debiti scaduti superano soglie precise, l'ente DEVE segnalare la situazione all'imprenditore e all'organo di controllo, invitandolo a valutare la composizione negoziata. È il cuore del lato ENTE della piattaforma.`,
    esempio: `Se un'impresa con dipendenti accumula contributi INPS scaduti da oltre 90 giorni oltre il 30% del dovuto dell'anno prima e comunque oltre 15.000 euro, l'INPS invia la segnalazione con l'invito ad attivarsi.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-ii/capo-iii/art25novies.html`,
  },
  {
    numero: `63`,
    rubrica: `Transazione su crediti tributari e contributivi`,
    capo: `Parte Prima - Titolo IV (Strumenti di regolazione della crisi) - Capo I (Accordi) - Sezione II (Accordi di ristrutturazione, convenzione di moratoria e transazione su crediti tributari e contributivi)`,
    testo: `1. Nell'ambito delle trattative che precedono la stipulazione degli accordi di ristrutturazione di cui agli articoli 57, 60 e 61 il debitore può proporre il pagamento, parziale o anche dilazionato, dei tributi e dei relativi accessori amministrati dalle agenzie fiscali, nonché dei contributi e premi amministrati dagli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie e dei relativi accessori, sorti sino alla data di presentazione della proposta di transazione. In tali casi l'attestazione del professionista indipendente di cui all'articolo 57, comma 4, relativamente ai crediti fiscali, previdenziali e assicurativi, ha ad oggetto anche la convenienza del trattamento proposto rispetto alla liquidazione giudiziale, se gli accordi hanno carattere liquidatorio, e la sussistenza di un trattamento non deteriore rispetto alla liquidazione giudiziale, quando è prevista la continuità dell'impresa.
2. La proposta di transazione, unitamente alla documentazione di cui agli articoli 57, 60 e 61, è depositata presso gli uffici indicati dall'articolo 88, comma 5. Alla proposta di transazione è allegata la dichiarazione sostitutiva, resa dal debitore o dal suo legale rappresentante ai sensi dell'articolo 47 del d.P.R. 28 dicembre 2000, n. 445, che la documentazione di cui al periodo precedente rappresenta fedelmente e integralmente la situazione dell'impresa, con particolare riguardo alle poste attive del patrimonio. Si applicano le disposizioni di cui all'articolo 88, comma 5, terzo e quarto periodo. L'adesione alla proposta è espressa con la sottoscrizione dell'atto negoziale da parte del Direttore della competente Direzione dell'Agenzia delle entrate e, ove sia competente una Direzione provinciale, la sottoscrizione è apposta previo parere conforme della relativa Direzione regionale. Quando la proposta ha oggetto tributi amministrati dall'Agenzia delle entrate e prevede una falcidia del debito originario, comprensivo dei relativi accessori, superiore alla percentuale e all'importo definiti con apposito provvedimento del Direttore dell'Agenzia delle entrate, il parere conforme di cui al quarto periodo è espresso dalla struttura centrale individuata con il medesimo provvedimento. Per i tributi amministrati dall'Agenzia delle dogane e dei monopoli l'adesione alla proposta è espressa dalle competenti Direzioni territoriali, dalla competente Direzione territoriale interprovinciale ovvero da ciascuna Direzione centrale per gli atti impositivi direttamente emessi. Per i contributi previdenziali amministrati dall'Istituto nazionale della previdenza sociale l'adesione alla proposta è espressa con la sottoscrizione dell'atto negoziale da parte del Direttore dell'ufficio territoriale competente su decisione del Direttore regionale. L'atto è sottoscritto anche dall'agente della riscossione in ordine al trattamento degli oneri di riscossione di cui all'articolo 17 del decreto legislativo 13 aprile 1999, n. 112. L'adesione espressa sulla proposta di transazione equivale a sottoscrizione dell'accordo di ristrutturazione. Ai fini del comma 3, l'eventuale adesione dei creditori deve intervenire entro novanta giorni dal deposito della proposta di transazione. Se la proposta di transazione è modificata, il predetto termine è aumentato di sessanta giorni decorrenti dal deposito della modifica della proposta presso gli uffici indicati dall'articolo 88, comma 5. Nei casi in cui la modifica contiene una nuova proposta, il termine di cui al periodo precedente è aumentato di ulteriori novanta giorni.
3. La domanda di omologazione è proposta una volta ottenuta l'adesione o, in difetto, decorsi i termini di cui al comma 2, undicesimo e dodicesimo periodo. Il debitore avvisa dell'iscrizione della domanda nel registro delle imprese l'amministrazione finanziaria e gli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie mediante comunicazione inviata a mezzo posta elettronica certificata alle sedi territoriali e regionali competenti sulla base dell'ultimo domicilio fiscale dell'istante. Per l'amministrazione finanziaria e gli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie, il termine per l'opposizione di cui all'articolo 48, comma 4, decorre dalla ricezione dell'avviso.
4. Il tribunale omologa gli accordi di ristrutturazione anche in mancanza di adesione, che comprende il voto contrario, da parte dell'amministrazione finanziaria o degli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie quando, anche sulla base delle risultanze della relazione del professionista indipendente, l'adesione è determinante ai fini del raggiungimento delle percentuali di cui agli articoli 57, comma 1, e 60, comma 1, e ricorrono congiuntamente le seguenti condizioni, oggetto di specifica valutazione da parte del tribunale: a) l'accordo non ha carattere liquidatorio; b) il credito complessivo vantato dagli altri creditori aderenti agli accordi di ristrutturazione è pari ad almeno un quarto dell'importo complessivo dei crediti; c) il soddisfacimento dell'amministrazione finanziaria o dei predetti enti è non deteriore rispetto all'alternativa della liquidazione giudiziale alla data della proposta; d) il soddisfacimento dei crediti dell'amministrazione finanziaria e degli enti gestori di forme di previdenza o assistenza obbligatorie è almeno pari al 50 per cento dell'ammontare dei crediti di ciascun ente creditore, esclusi sanzioni ed interessi, fermo restando il pagamento degli interessi di dilazione al tasso legale vigente nel corso di tale periodo.
5. Se l'ammontare complessivo dei crediti vantati dagli altri creditori aderenti agli accordi di ristrutturazione è inferiore a un quarto dell'importo complessivo dei crediti, oppure non vi sono altri creditori aderenti, la disposizione di cui al comma 4 trova applicazione, fatto salvo il rispetto delle condizioni di cui alle lettere a) e c) del medesimo comma 4, se la percentuale di soddisfacimento dei crediti dell'amministrazione finanziaria e degli enti gestori di forme di previdenza o assistenza obbligatorie è almeno pari al 60 per cento dell'ammontare dei crediti di ciascun ente creditore, esclusi sanzioni ed interessi, e la dilazione di pagamento richiesta non eccede il periodo di dieci anni, fermo restando il pagamento dei relativi interessi di dilazione al tasso legale vigente nel corso di tale periodo.
6. Le disposizioni di cui ai commi 4 e 5 non trovano applicazione se si verifica una delle seguenti ipotesi: a) se, fatta salva l'ipotesi cui all'articolo 58, nei cinque anni precedenti il deposito della proposta il debitore ha concluso una transazione nell'ambito degli accordi regolati dal presente articolo avente a oggetto debiti della stessa natura, risolta di diritto; b) se ricorrono congiuntamente le seguenti condizioni: 1) il debito nei confronti dell'amministrazione finanziaria e degli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie maturato sino al giorno anteriore a quello del deposito della proposta di transazione fiscale è pari o superiore all'ottanta per cento dell'importo complessivo dei debiti maturati dall'impresa alla medesima data; 2) il debito, tributario o previdenziale, deriva prevalentemente da omessi versamenti, anche solo parziali, di imposte dichiarate o contributi nel corso di almeno cinque periodi d'imposta, anche non consecutivi, oppure deriva, per almeno un terzo del complessivo debito oggetto di transazione con i creditori pubblici, dall'accertamento di violazioni realizzate mediante l'utilizzo di documentazione falsa o per operazioni inesistenti, mediante artifici o raggiri, condotte simulatorie o fraudolente.
7. L'ipotesi di cui al comma 6, lettera a), si verifica anche quando il proponente ha proseguito, ancorché solo parzialmente, a seguito di fusione o scissione, cessione di azienda, anche di fatto, conferimento o affitto di azienda ovvero a seguito di atti produttivi di effetti analoghi, l'attività esercitata da un soggetto che, nel corso dei cinque anni precedenti il deposito della proposta, ha concluso una transazione risolta di diritto ai sensi del comma 8, ovvero risponde a qualsiasi titolo di debiti tributari o contributivi del debitore originario.
8. La transazione conclusa nell'ambito degli accordi di ristrutturazione è risolta di diritto se il debitore non esegue integralmente, entro sessanta giorni dalle scadenze previste, i pagamenti dovuti alle agenzie fiscali e agli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie.`,
    soglie: `CRAM DOWN FISCALE (commi 4-5): adesione dei creditori entro 90 giorni dal deposito della proposta (+60 giorni in caso di modifica; +ulteriori 90 giorni se la modifica contiene nuova proposta). Omologazione forzosa (comma 4): richiede che i crediti degli altri creditori aderenti siano pari ad almeno UN QUARTO (1/4) dell'importo complessivo E soddisfacimento del creditore pubblico almeno pari al 50% dei crediti di ciascun ente (esclusi sanzioni e interessi). In assenza/insufficienza di altri aderenti (comma 5): soddisfacimento almeno pari al 60% e dilazione non eccedente 10 anni. Esclusioni (comma 6): transazione precedente risolta nei 5 anni precedenti; debito fiscale/previdenziale pari o superiore all'80% del totale debiti; debito derivante da omessi versamenti in almeno 5 periodi d'imposta o, per almeno 1/3, da violazioni fraudolente. Risoluzione di diritto (comma 8): mancato pagamento integrale entro 60 giorni dalle scadenze.`,
    inParoleSemplici: `Disciplina la transazione fiscale e contributiva negli accordi di ristrutturazione: consente di proporre a Fisco ed enti previdenziali un pagamento parziale e/o dilazionato dei tributi e contributi. È la sede del cosiddetto «cram down fiscale», che permette al tribunale di omologare anche senza l'adesione dell'ente, a certe condizioni.`,
    esempio: `L'impresa propone all'Agenzia delle Entrate di pagare il 40% del debito IVA in cinque anni; se l'offerta è più conveniente della liquidazione e l'ente non aderisce, il tribunale può comunque omologare (cram down).`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-iv/capo-i/sezione-ii/art63.html`,
  },
  {
    numero: `88`,
    rubrica: `Trattamento dei crediti tributari e contributivi`,
    capo: `Parte Prima - Titolo IV - Capo III (Concordato preventivo) - Sezione I (Finalità e contenuti del concordato preventivo)`,
    testo: `1. Con il piano di concordato il debitore, esclusivamente mediante proposta presentata ai sensi del presente articolo, può proporre il pagamento, parziale o anche dilazionato, dei tributi e dei relativi accessori amministrati dalle agenzie fiscali nonché dei contributi e premi amministrati dagli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie e dei relativi accessori, se il piano ne prevede la soddisfazione in misura non inferiore a quella realizzabile, in ragione della collocazione preferenziale, sul ricavato in caso di liquidazione giudiziale, avuto riguardo al valore attribuibile ai beni o ai diritti sui quali sussiste la causa di prelazione, indicato nella relazione di un professionista indipendente. Fermo restando per il concordato in continuità aziendale il rispetto dell'articolo 84, commi 6 e 7, se il credito tributario e contributivo è assistito da privilegio, la percentuale, i tempi di pagamento e le eventuali garanzie non possono essere inferiori o meno vantaggiosi rispetto a quelli offerti ai creditori che hanno un grado di privilegio inferiore o a quelli che hanno una posizione giuridica e interessi economici omogenei a quelli delle agenzie e degli enti di cui al primo periodo. Se il credito tributario o contributivo ha natura chirografaria, anche a seguito di degradazione per incapienza, il trattamento non può essere differenziato rispetto a quello degli altri crediti chirografari ovvero, nel caso di suddivisione in classi, dei crediti rispetto ai quali è previsto un trattamento più favorevole.
2. L'attestazione del professionista indipendente, relativamente ai crediti tributari e contributivi, ha ad oggetto anche, nel concordato liquidatorio, la convenienza del trattamento proposto rispetto alla liquidazione giudiziale e, nel concordato in continuità aziendale, la sussistenza di un trattamento non deteriore dei medesimi crediti rispetto alla liquidazione giudiziale.
3. Nel concordato liquidatorio il tribunale omologa il concordato anche in mancanza di adesione, che comprende il voto contrario, da parte dell'amministrazione finanziaria o degli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie quando l'adesione è determinante ai fini del raggiungimento delle percentuali di cui all'articolo 109, comma 1, e, anche sulla base delle risultanze della relazione del professionista indipendente, la proposta di soddisfacimento della predetta amministrazione o degli enti gestori di forme previdenza, assistenza e assicurazioni obbligatorie è conveniente rispetto all'alternativa della liquidazione giudiziale.
4. Nel concordato in continuità aziendale, ferme restando le altre condizioni previste dall'articolo 112, comma 2, il tribunale omologa il concordato anche in mancanza di adesione, che comprende il voto contrario, da parte dell'amministrazione finanziaria o degli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie, se la proposta di soddisfacimento della predetta amministrazione o degli enti gestori di forme di previdenza, assistenza e assicurazioni obbligatorie risulta non deteriore rispetto all'alternativa della liquidazione giudiziale. Nell'ipotesi di cui al primo periodo il tribunale omologa se tale adesione è determinante ai fini del raggiungimento della maggioranza delle classi prevista dall'articolo 112, comma 2, lettera d), oppure se la stessa maggioranza è raggiunta escludendo dal computo le classi dei creditori di cui al comma 1. In ogni caso, ai fini della condizione prevista dall'articolo 112, comma 2, lettera d), numeri 1) e 2), l'adesione dei creditori pubblici deve essere espressa.
5. Copia della proposta e della relativa documentazione, contestualmente al deposito presso il tribunale, è presentata agli uffici competenti sulla base dell'ultimo domicilio fiscale del debitore. La documentazione di cui al primo periodo, unitamente alla copia delle dichiarazioni fiscali per le quali non è pervenuto l'esito dei controlli automatici nonché delle dichiarazioni integrative presentate fino alla data di presentazione della domanda di trattamento dei crediti tributari e contributivi, è presentata, per l'Agenzia delle entrate, alla competente Direzione provinciale o regionale, per l'Agenzia delle dogane e dei monopoli, alle competenti Direzioni territoriali e alla competente Direzione territoriale interprovinciale, ovvero alla Direzione centrale per gli atti impositivi direttamente emessi e, infine, per gli enti previdenziali e assicurativi, alla competente Direzione provinciale. L'agente della riscossione, non oltre trenta giorni dalla data della presentazione, deve trasmettere al debitore una certificazione attestante l'entità del debito iscritto a ruolo scaduto o sospeso. Gli altri uffici indicati nei precedenti periodi, nello stesso termine, devono procedere alla liquidazione dei tributi risultanti dalle dichiarazioni e alla notifica dei relativi avvisi di irregolarità, di accertamento, di liquidazione e di addebito, unitamente a una certificazione attestante l'entità del debito derivante da atti di accertamento, ancorché non definitivi, per la parte non iscritta a ruolo, nonché dai ruoli vistati ma non ancora consegnati all'agente della riscossione. Dopo la nomina del commissario giudiziale copia dei predetti avvisi e delle certificazioni deve essergli trasmessa per gli adempimenti previsti dagli articoli 105, comma 1, e 106.
6. Per i tributi amministrati dall'Agenzia delle entrate il voto sulla proposta è espresso ai sensi dell'articolo 107 dalla competente Direzione, su parere conforme della relativa Direzione regionale ove competente sia una Direzione provinciale. Per i tributi amministrati dall'Agenzia delle dogane e dei monopoli il voto sulla proposta è espresso ai sensi dell'articolo 107 dalle competenti Direzioni territoriali, dalla competente Direzione territoriale interprovinciale ovvero da ciascuna Direzione centrale per gli atti impositivi direttamente emessi. Per i contributi previdenziali amministrati dall'Istituto nazionale della previdenza sociale e per i premi amministrati dall'Istituto nazionale dell'assicurazione contro gli infortuni sul lavoro il voto sulla proposta è espresso ai sensi dell'articolo 107 dalla competente Direzione territoriale su decisione del Direttore regionale.
7. Il voto è espresso dall'agente della riscossione limitatamente agli oneri di riscossione di cui all'articolo 17 del decreto legislativo 13 aprile 1999, n. 112.`,
    soglie: `L'agente della riscossione e gli altri uffici trasmettono le certificazioni sul debito entro 30 giorni dalla presentazione della proposta (comma 5). Cram down fiscale nel concordato (commi 3-4): omologazione anche senza adesione del creditore pubblico quando l'adesione è determinante e il soddisfacimento è conveniente (concordato liquidatorio) o non deteriore (continuità) rispetto alla liquidazione giudiziale. L'articolo non fissa soglie in euro né percentuali minime fisse (a differenza dell'art. 63): il parametro è il confronto con l'alternativa liquidatoria.`,
    inParoleSemplici: `È l'equivalente della transazione fiscale ma dentro il concordato preventivo: regola come si trattano i crediti tributari e contributivi, la percentuale e i tempi di pagamento, e prevede anch'essa la possibilità di omologazione forzosa (cram down) al ricorrere dei presupposti.`,
    esempio: `Nel piano di concordato l'impresa destina ai crediti privilegiati dell'Erario una somma non inferiore a quanto ricaverebbero in una liquidazione, condizione per poter chiedere l'omologa anche senza il voto favorevole del Fisco.`,
    fonteUrl: `https://www.brocardi.it/codice-crisi-impresa/parte-prima/titolo-iv/capo-iii/sezione-i/art88.html`,
  },
];

export interface DecretoAttuativo {
  titolo: string;
  contenuto: string;
  fonteUrl: string;
}

export const DECRETO_ATTUATIVO: DecretoAttuativo = {
  titolo: `Decreto dirigenziale del Ministero della Giustizia 28 settembre 2021 - "Composizione negoziata per la soluzione della crisi d'impresa", di attuazione del decreto-legge 24 agosto 2021, n. 118 (poi trasfuso nel Codice della crisi, D.Lgs. 14/2019, artt. 12 ss.).`,
  contenuto: `Il decreto dà attuazione alle previsioni oggi contenute nell'art. 13, comma 2, CCII e definisce gli strumenti operativi disponibili sulla piattaforma telematica nazionale della composizione negoziata. Si articola in una parte dispositiva e in allegati/sezioni che comprendono: (1) TEST PRATICO per la verifica della ragionevole perseguibilità del risanamento - strumento di autodiagnosi che rapporta l'entità del debito da ristrutturare ai flussi finanziari annui liberi (a regime) che l'impresa è in grado di generare, per orientare l'imprenditore sulla concreta perseguibilità del risanamento; (2) LISTA DI CONTROLLO (CHECK-LIST) PARTICOLAREGGIATA per la redazione del piano di risanamento, adeguata anche alle micro, piccole e medie imprese, con indicazioni operative articolate su: organizzazione dell'impresa e rilevazione della situazione, individuazione delle strategie di intervento, elaborazione del piano e delle proiezioni dei flussi finanziari, verifica della coerenza e sostenibilità del debito, disciplina dei gruppi di imprese; (3) PROTOCOLLO DI CONDUZIONE della composizione negoziata, che guida l'esperto lungo tutte le fasi dell'incarico (verifica dell'indipendenza e accettazione, convocazione dell'imprenditore, conduzione delle trattative e degli incontri con i creditori, fino alla relazione finale e all'archiviazione); (4) indicazioni sulla FORMAZIONE degli esperti, sulla struttura della PIATTAFORMA TELEMATICA e sulla modulistica (istanza online, dichiarazione di accettazione dell'incarico, possibili proposte alle parti). AGGIORNAMENTI SUCCESSIVI: con l'entrata a regime del Codice della crisi (D.Lgs. 83/2022, che ha trasfuso la composizione negoziata nel CCII a decorrere dal 15 luglio 2022) i contenuti sono stati confermati e adeguati; il Ministero della Giustizia ha adottato il Decreto dirigenziale 21 marzo 2023, che ha recepito l'aggiornamento del documento (test pratico e check-list particolareggiata) predisposto dalla Commissione di studio istituita con decreto 22 aprile 2021.`,
  fonteUrl: `https://www.giustizia.it/giustizia/it/mg_1_8_1.page?contentId=SDC348467`,
};

export interface VoceGlossario {
  termine: string;
  sigla?: string;
  definizione: string;
  esempio: string;
  formula?: string;
  articoliCorrelati?: string[];
}

export const GLOSSARIO: VoceGlossario[] = [
  {
    termine: 'Composizione negoziata della crisi',
    sigla: 'CNC',
    definizione:
      'Percorso volontario e riservato in cui un esperto indipendente affianca l’imprenditore nelle trattative con i creditori per superare la crisi e risanare l’impresa, prima e fuori dal tribunale. Non è una procedura concorsuale: l’imprenditore resta alla guida dell’azienda.',
    esempio:
      'Un’impresa con tensioni di cassa ma ordini ancora solidi chiede l’esperto alla Camera di commercio e apre un tavolo con banche e fornitori, senza spossessarsi dell’azienda.',
    articoliCorrelati: ['12', '13', '17'],
  },
  {
    termine: 'Crisi',
    definizione:
      'Stato del debitore che rende probabile l’insolvenza e si manifesta con l’inadeguatezza dei flussi di cassa prospettici a far fronte alle obbligazioni nei successivi dodici mesi. È una difficoltà ancora reversibile, che guarda al futuro (12 mesi) più che al passato.',
    esempio:
      'Le entrate previste per l’anno prossimo non bastano a coprire rate di mutuo e stipendi: l’impresa è in crisi, anche se oggi paga ancora tutti.',
    articoliCorrelati: ['2'],
  },
  {
    termine: 'Insolvenza',
    definizione:
      'Stato del debitore che non è più in grado di soddisfare regolarmente le proprie obbligazioni, manifestato da inadempimenti o altri fatti esteriori. È lo stadio più grave e strutturale rispetto alla crisi.',
    esempio:
      'L’impresa ha smesso di pagare stabilmente fornitori, dipendenti e banche: non è più una difficoltà passeggera, è insolvenza.',
    articoliCorrelati: ['2'],
  },
  {
    termine: 'DSCR (Debt Service Coverage Ratio)',
    sigla: 'DSCR',
    definizione:
      'Indice che misura la capacità dell’impresa di ripagare il debito con la cassa che genera: rapporta i flussi di cassa disponibili al servizio del debito (rate di capitale + interessi) di un dato periodo. Se è sotto 1, la cassa prodotta non basta a coprire il debito in scadenza; sopra 1 c’è un margine.',
    formula:
      'DSCR = Flussi di cassa disponibili al servizio del debito ÷ (Quota capitale + Interessi in scadenza)',
    esempio:
      'Un’impresa genera 120.000 € di cassa libera e deve pagare 100.000 € tra rate e interessi: DSCR = 1,2 — c’è un margine del 20%. Se ne generasse solo 80.000, DSCR = 0,8 — segnale di crisi.',
    articoliCorrelati: ['3'],
  },
  {
    termine: 'EBITDA',
    sigla: 'EBITDA',
    definizione:
      'Margine operativo lordo: l’utile prima di interessi, imposte, svalutazioni e ammortamenti. Approssima la redditività della sola gestione operativa e la cassa che l’attività caratteristica è in grado di produrre, prima delle scelte finanziarie e fiscali.',
    formula:
      'EBITDA = Valore della produzione − Costi operativi (esclusi ammortamenti, svalutazioni, interessi e imposte)',
    esempio:
      'Ricavi 1.000.000 €, costi operativi (senza ammortamenti) 850.000 € → EBITDA = 150.000 €. È il punto di partenza per capire quanta cassa l’impresa può destinare a debito e investimenti.',
  },
  {
    termine: 'Cram down (fiscale)',
    definizione:
      'Meccanismo che consente al tribunale di omologare un accordo di ristrutturazione o un concordato anche senza l’adesione dell’Erario o degli enti previdenziali, quando la proposta è per loro più conveniente della liquidazione e ricorrono le condizioni di legge. Evita che il diniego di un singolo creditore pubblico blocchi il risanamento.',
    esempio:
      'L’impresa offre al Fisco il 40% del debito, più di quanto ricaverebbe dalla liquidazione. Il Fisco non aderisce, ma il tribunale omologa ugualmente: è il cram down.',
    articoliCorrelati: ['63', '88'],
  },
  {
    termine: 'Transazione fiscale e contributiva',
    definizione:
      'Accordo con Fisco ed enti previdenziali per pagare in misura ridotta e/o dilazionata tributi e contributi, all’interno di un accordo di ristrutturazione o di un concordato. È lo strumento che rende trattabili i debiti verso enti pubblici come INPS e Agenzia delle Entrate.',
    esempio:
      'Nel piano, il debito IVA viene proposto al 50% in cinque anni e i contributi INPS al 60%: la transazione, se omologata, chiude quelle posizioni.',
    articoliCorrelati: ['63', '88'],
  },
  {
    termine: 'Misure protettive',
    definizione:
      'Misure temporanee, richieste dall’imprenditore, che impediscono ai creditori di avviare o proseguire azioni esecutive e cautelari sul patrimonio durante le trattative, per non pregiudicare il risanamento. Sono l’«ombrello» della composizione negoziata.',
    esempio:
      'Pubblicate le misure protettive, una banca non può escutere il pegno né un fornitore avviare un pignoramento per crediti anteriori finché durano le trattative.',
    articoliCorrelati: ['18', '19', '2'],
  },
  {
    termine: 'Misure cautelari',
    definizione:
      'Provvedimenti emessi dal giudice per salvaguardare il patrimonio o l’impresa e assicurare il buon esito delle trattative, su richiesta dell’imprenditore o dei creditori.',
    esempio:
      'Il tribunale nomina un custode o vieta un atto dispositivo che metterebbe a rischio la garanzia dei creditori.',
    articoliCorrelati: ['19', '2'],
  },
  {
    termine: 'Esperto',
    definizione:
      'Professionista indipendente, iscritto in un apposito elenco e nominato da una commissione, che agevola le trattative tra imprenditore e creditori. Non decide e non sostituisce l’imprenditore: facilita, verifica la perseguibilità del risanamento e vigila sulla correttezza.',
    esempio:
      'L’esperto convoca banche e fornitori, verifica i numeri del piano e, se un atto danneggia i creditori, iscrive il proprio dissenso.',
    articoliCorrelati: ['12', '13', '16'],
  },
  {
    termine: 'Creditori pubblici qualificati',
    definizione:
      'INPS, INAIL, Agenzia delle Entrate e Agenzia delle Entrate-Riscossione. Quando i debiti scaduti verso di loro superano soglie precise, hanno l’obbligo di segnalare la situazione all’imprenditore e all’organo di controllo, invitandolo a valutare la composizione negoziata.',
    esempio:
      'L’INPS rileva contributi scaduti oltre soglia e invia la segnalazione con l’invito ad attivarsi: è spesso il primo campanello d’allarme formale.',
    articoliCorrelati: ['25-novies'],
  },
  {
    termine: 'Concordato semplificato',
    definizione:
      'Strumento liquidatorio riservato a chi ha condotto lealmente la composizione negoziata senza trovare un accordo: si propone al tribunale la liquidazione del patrimonio senza voto dei creditori, con specifiche garanzie di convenienza.',
    esempio:
      'Falliti i tentativi di accordo pur essendosi comportato correttamente, l’imprenditore propone di liquidare i beni assicurando ai creditori almeno quanto otterrebbero dalla liquidazione giudiziale.',
    articoliCorrelati: ['25-sexies', '23'],
  },
  {
    termine: 'Accordi di ristrutturazione dei debiti',
    definizione:
      'Strumento negoziale, omologato dal tribunale, con cui l’impresa ristruttura l’indebitamento con creditori che rappresentano una quota qualificata dei crediti. È uno degli sbocchi possibili delle trattative.',
    esempio:
      'L’impresa raggiunge l’accordo con banche che detengono il 65% dei crediti e lo fa omologare: le nuove scadenze diventano vincolanti secondo i termini dell’accordo.',
    articoliCorrelati: ['23', '63'],
  },
  {
    termine: 'Test pratico di risanamento',
    definizione:
      'Strumento di autodiagnosi previsto dal decreto attuativo: rapporta l’entità del debito da ristrutturare ai flussi finanziari liberi che l’impresa può generare a regime, per orientare l’imprenditore sulla concreta perseguibilità del risanamento.',
    esempio:
      'Se il debito da ristrutturare è pari a molte volte i flussi liberi annui, il test segnala che il risanamento richiede interventi più incisivi (dismissioni, nuova finanza, ristrutturazione del debito).',
    articoliCorrelati: ['13', '17'],
  },
];

export interface SogliaParametro {
  ambito: string;
  descrizione: string;
  valore: string;
  riferimento: string;
}

export const SOGLIE: SogliaParametro[] = [
  {
    ambito: 'Segnalazione INPS — imprese CON lavoratori',
    descrizione:
      'Ritardo di oltre 90 giorni nel versamento di contributi previdenziali di ammontare superiore alla soglia (entrambi i requisiti).',
    valore: '> 30% dei contributi dovuti nell’anno precedente E > 15.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Segnalazione INPS — imprese SENZA lavoratori',
    descrizione: 'Ritardo di oltre 90 giorni nel versamento di contributi previdenziali.',
    valore: '> 5.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Segnalazione INAIL',
    descrizione: 'Debito per premi assicurativi scaduto da oltre 90 giorni e non versato.',
    valore: '> 5.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Segnalazione Agenzia delle Entrate (IVA)',
    descrizione:
      'Debito IVA scaduto e non versato risultante dalle liquidazioni periodiche, superiore alla soglia e comunque non inferiore al 10% del volume d’affari dell’anno precedente; segnalazione in ogni caso oltre 20.000 €.',
    valore: '> 5.000 € (e ≥ 10% del volume d’affari) — in ogni caso se > 20.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Segnalazione Agenzia Entrate-Riscossione — imprese individuali',
    descrizione: 'Crediti affidati, scaduti da oltre 90 giorni.',
    valore: '> 100.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Segnalazione Agenzia Entrate-Riscossione — società di persone',
    descrizione: 'Crediti affidati, scaduti da oltre 90 giorni.',
    valore: '> 200.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Segnalazione Agenzia Entrate-Riscossione — altre società',
    descrizione: 'Crediti affidati, scaduti da oltre 90 giorni.',
    valore: '> 500.000 €',
    riferimento: '25-novies',
  },
  {
    ambito: 'Impresa minore (soglie di non fallibilità)',
    descrizione:
      'I tre requisiti devono ricorrere congiuntamente, riferiti ai tre esercizi antecedenti. Sotto tutte e tre le soglie, l’impresa è «minore».',
    valore: 'Attivo ≤ 300.000 € — Ricavi ≤ 200.000 € — Debiti ≤ 500.000 €',
    riferimento: '2',
  },
  {
    ambito: 'Orizzonte della crisi',
    descrizione: 'La probabilità di insolvenza si valuta sui flussi di cassa prospettici.',
    valore: '12 mesi',
    riferimento: '2',
  },
];
